name: Build and publish website

on:
  schedule:
     #Build once per day, at 03:15 UTC
    - cron: "15 3 * * *"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: clone fmhy
        run: |
          git clone --depth 1 --branch main \
            https://github.com/fmhy/edit.git/ \
            source
   
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 25.2.1
          cache: pnpm
          cache-dependency-path: source/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: source
        run: pnpm install --frozen-lockfile
        
      - name: Build FMHY website
        working-directory: source
        run: |
          pnpm docs:build -- --base /


      - name: Copy generated files into deployment directory
        working-directory: source
        run: |
          rm -rf _site
          mkdir -p _site
          cp -a docs/.vitepress/dist _site

       
       # This redirect is used by the www deployment below.
      - name: Add www-to-apex redirect
        working-directory: source
        run: |
          printf '%s\n' \
            '//www.fmhy.vencat.dev/* https://fmhy.vencat.dev/:splat 301!' \
            '//www.vencat.dev/* https://vencat.dev/:splat 301!' \
            '//www.vencat.dev/* https://vencat.dev/:splat 301!' \
            > _site/_redirects

      - name: Publish to existing custom domain
        uses: actions/upload-pages-artifact@v3
        with:
          path: source/_site
