name: Build and publish website

on:
  schedule:
  #Build once per day, at 03:15 UTC
    - cron: "15 3 * * *"

  workflow_dispatch:

# added perms to make sure
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: clone fmhy
        run: |
          git clone --depth 1 --branch main \
            https://github.com/fmhy/edit.git/ \
            "$RUNNER_TEMP/site"
   
      - name: set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.2

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install dependencies
        working-directory: ${{ runner.temp }}/site
        run: |
          pnpm install --frozen-lockfile
        
      - name: build fmhy
        working-directory: ${{ runner.temp }}/site
        run: |
          pnpm docs:build --base /
          ls "$RUNNER_TEMP/site/docs/.vitepress/dist"

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ runner.temp }}/site/docs/.vitepress/dist


  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
